# The material of the item(it will not be visible on the client)
# You can change this, but this has no effect to the game or to the player.
# For usable materials look here: https://github.com/X00LA/HeartDrops/wiki/Config
material: 'REDSTONE'
# The chance for a double heal.
# You can increase or decrease the chance for your players to "win" a double heal.
doubleHealChance: 0.2
# The delay between the spawn of a heart particle.
# You can decrease the delay so the heart spawn faster or increase it to let the players wait for their energy.
particleTime: 15
# The sound of an item pickup.
# You can use different sound.
# For a list of available sounds look here: https://github.com/X00LA/HeartDrops/wiki/Config
pickupsound: 'ENTITY_PLAYER_LEVELUP'
# The volume of the pickup sound.
# Increase or decrease the volume as your want.
pickupvolume: 0.5
# The pitch of the pickup sound.
# Increase or decrease the pitch to make the sound a bit... courious.
pickuppitch: 0
# The amount to heal the player.
# 1 means that 1 heart heals half a player heart. So 2 heals a full player heart.
healAmount: 1
###########################################################################################################
# Here you can play with the variables to increase or decrease the amount of given hearts.                #
# Pattern: entitytype : dropchance : minimum drop amount : maximumdropamount : maximum of hearts per item #
# Example:    ZOMBIE  :     0.2    :         0           :         1         :              1             #
###########################################################################################################
entities:
  - 'ENDERMAN : 0.2 : 0 : 1 : 1'
  - 'CREEPER : 0.2 : 0 : 1 : 1'
  - 'ZOMBIE : 0.2 : 0 : 1 : 1'
  - 'PIG_ZOMBIE : 0.2 : 0 : 1 : 1'
  - 'SKELETON : 0.2 : 0 : 1 : 1'
  - 'GHAST : 0.2 : 0 : 1 : 1'
  - 'SPIDER : 0.2 : 0 : 1 : 1'
  - 'CAVE_SPIDER : 0.2 : 0 : 1 : 1'
  - 'SLIME : 0.2 : 0 : 1 : 1'
  - 'BLAZE : 0.2 : 0 : 1 : 1'
  - 'MAGMA_CUBE : 0.2 : 0 : 1 : 1'
  - 'WITCH : 0.2 : 0 : 1 : 1'
  - 'ENDERMITE : 0.2 : 0 : 1 : 1'
  - 'ENDER_DRAGON : 0.2 : 0 : 1 : 1'
  - 'WITHER : 0.2 : 0 : 1 : 1'
  - 'SILVERFISH : 0.2 : 0 : 1 : 1'
#########################################################################
# Uncomment the following entries if you want hearts when killing them. #
#########################################################################
# - 'CHICKEN : 0.2 : 0 : 1 : 1'
# - 'COW : 0.2 : 0 : 1 : 1'
# - 'GIANT : 0.2 : 0 : 1 : 1'
# - 'GUARDIAN : 0.2 : 0 : 1 : 1'
# - 'HORSE : 0.2 : 0 : 1 : 1'
# - 'IRON_GOLEM : 0.2 : 0 : 1 : 1'
# - 'MUSHROOM_COW : 0.2 : 0 : 1 : 1'
# - 'OCELOT : 0.2 : 0 : 1 : 1'
# - 'PIG : 0.2 : 0 : 1 : 1'
# - 'PLAYER : 0.2 : 0 : 1 : 1'
# - 'RABBIT : 0.2 : 0 : 1 : 1'
# - 'SHEEP : 0.2 : 0 : 1 : 1'
# - 'SNOWMAN : 0.2 : 0 : 1 : 1'
# - 'SQUID : 0.2 : 0 : 1 : 1'
# - 'VILLAGER : 0.2 : 0 : 1 : 1'
# - 'WOLF : 0.2 : 0 : 1 : 1'
