name: HeartDrops
main: eu.xoola.HeartDrops.HeartDrops
version: 1.5.3
author: O_Shadow_O - X00LA
depend: [ProtocolLib]
commands:
    heartdrops:
      description: Heartdrops Main Command
      usage: /heartdrops [args]
      permission: heartdrops.admin
